name = "Fermionic"
uuid = "9854c450-6826-470b-b7cd-d3803b32f4ba"
authors = ["Marco Di Tullio", "Mario Galante", "Raul Rossignoli"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
