name = "Fermionic"
uuid = "9854c450-6826-470b-b7cd-d3803b32f4ba"
authors = ["Marco Di Tullio", "Raul Rossignoli", "Agustín Cianciulli"]
version = "1.3.3"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.4"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets"]
